language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true react-test npm test

after_success:
  - docker build -t arumiantsau/complex-client ./client
  - docker build -t arumiantsau/complex-nginx ./nginx
  - docker build -t arumiantsau/complex-server ./server
  - docker build -t arumiantsau/complex-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push arumiantsau/complex-client
  - docker push arumiantsau/complex-nginx
  - docker push arumiantsau/complex-server
  - docker push arumiantsau/complex-worker
