language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true react-test npm test

after_success:
  - docker build -t arumiantsau/complex-client ./client
  - docker build -t arumiantsau/complex-nginx ./nginx
  - docker build -t arumiantsau/complex-server ./server
  - docker build -t arumiantsau/complex-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push arumiantsau/complex-client
  - docker push arumiantsau/complex-nginx
  - docker push arumiantsau/complex-server
  - docker push arumiantsau/complex-worker
deploy:
  provider: elascticbeanstalk
  region: eu-central-1
  app: complex-docker
  env: Complexdocker-env
  bucket_name: elasticbeanstalk-eu-central-1-261262434766
  bucket_path: docker-complex
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY